version: '3.8'

services:
  frontend:
    build:
      context: ./papelaria-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./papelaria-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
      - db

  backend:
    build:
      context: ./papelaria-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=papelaria;User=root;Password=root;
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: papelaria
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: