version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: papelaria-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./papelaria-backend
    container_name: papelaria-backend
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;database=${MYSQL_DATABASE};user=root;password=${MYSQL_ROOT_PASSWORD}
    ports:
      - "5218:5218"
    depends_on:
      - mysql

  frontend:
    build: ./papelaria-frontend
    container_name: papelaria-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend