-- MySQL Script generated by MySQL Workbench
-- Mon May 26 21:41:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema papelaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema papelaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `papelaria` DEFAULT CHARACTER SET utf8mb3 ;
USE `papelaria` ;

-- -----------------------------------------------------
-- Table `papelaria`.`caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `papelaria`.`caixa` (
  `caixa_id` INT NOT NULL AUTO_INCREMENT,
  `caixa_Data` DATETIME NULL DEFAULT NULL,
  `caixa_Status` TINYINT NOT NULL,
  PRIMARY KEY (`caixa_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `papelaria`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `papelaria`.`item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_nome` VARCHAR(100) NOT NULL,
  `item_valor` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `papelaria`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `papelaria`.`produto` (
  `produto_codbarra` VARCHAR(100) NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  CONSTRAINT `fk_Produto_Item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `papelaria`.`item` (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `papelaria`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `papelaria`.`estoque` (
  `estoque_id` INT NOT NULL AUTO_INCREMENT,
  `estoque_quant` INT NULL DEFAULT NULL,
  `produtoItem_id` INT NOT NULL,
  PRIMARY KEY (`estoque_id`, `produtoItem_id`),
  INDEX `fk_Estoque_Produto1_idx` (`produtoItem_id` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Produto1`
    FOREIGN KEY (`produtoItem_id`)
    REFERENCES `papelaria`.`produto` (`item_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `papelaria`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `papelaria`.`venda` (
  `venda_id` INT NOT NULL AUTO_INCREMENT,
  `venda_Valor` FLOAT NULL DEFAULT NULL,
  `venda_Data` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`venda_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `papelaria`.`itemvenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `papelaria`.`itemvenda` (
  `item_venda_id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `venda_id` INT NOT NULL,
  `item_venda_quant` INT NULL DEFAULT NULL,
  PRIMARY KEY (`item_venda_id`),
  INDEX `fk_Item_has_Venda_Venda1_idx` (`venda_id` ASC) VISIBLE,
  INDEX `fk_Item_has_Venda_Item1_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_Item_has_Venda_Item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `papelaria`.`item` (`item_id`),
  CONSTRAINT `fk_Item_has_Venda_Venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `papelaria`.`venda` (`venda_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `papelaria`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `papelaria`.`servico` (
  `servico_disponivel` INT NULL DEFAULT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_Serviço_Item_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_Serviço_Item`
    FOREIGN KEY (`item_id`)
    REFERENCES `papelaria`.`item` (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `papelaria`.`vendacaixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `papelaria`.`vendacaixa` (
  `vendaCaixa_id` INT NOT NULL AUTO_INCREMENT,
  `vendaCaixa_idVenda` INT NOT NULL,
  `vendaCaixa_idCaixa` INT NOT NULL,
  PRIMARY KEY (`vendaCaixa_id`),
  INDEX `fk_Venda_has_Caixa_Caixa1_idx` (`vendaCaixa_idCaixa` ASC) VISIBLE,
  INDEX `fk_Venda_has_Caixa_Venda1_idx` (`vendaCaixa_idVenda` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_has_Caixa_Caixa1`
    FOREIGN KEY (`vendaCaixa_idCaixa`)
    REFERENCES `papelaria`.`caixa` (`caixa_id`),
  CONSTRAINT `fk_Venda_has_Caixa_Venda1`
    FOREIGN KEY (`vendaCaixa_idVenda`)
    REFERENCES `papelaria`.`venda` (`venda_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
